In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/drive/MyDrive/Task_1/Book2.csv')
print(data)

x=np.array(data[['x1','x2']])
y=np.array(data[['y']])
print(x)
print(y)

x_mean=np.mean(x,axis=0)
x_std=np.std(x,axis=0)

print(x_mean)
print(x_std)

x=(x-x_mean)/x_std
print(x)

x_b=np.c_[np.ones((len(x),1)),x]
print(x_b)

theta=np.zeros((x_b.shape[1],1))
print(theta)

alpha=0.01
iterations=1000

for i in range(iterations):
  y_pred=x_b.dot(theta)
  error=y_pred-y

  gradient=(2/len(y))*x_b.T.dot(error)
  theta=theta-(alpha*gradient)

print("optimized weights:",theta)

print("Optimized coefficients (theta):", theta[1:])
print("Optimized intercept:", theta[0])

data_test=pd.read_csv('/content/drive/MyDrive/Task_1/book_test.csv')
print(data_test)
x_test=np.array(data_test[['X1','X2']])
print(x_test)

x_test=(x_test-np.mean(x_test,axis=0))/np.std(x_test,axis=0)
print(x_test)

x_test_b=np.c_[np.ones((len(x_test),1)),x_test]
print(x_test_b)

y_predicted=x_test_b.dot(theta)
print("Predicted value for new input:", y_predicted)

   x1  x2    y
0   5   9  100
1   6   3  200
2   2   7  300
3   4   5  400
4   8   7  500
5   9   5  600
6   6   4  700
[[5 9]
 [6 3]
 [2 7]
 [4 5]
 [8 7]
 [9 5]
 [6 4]]
[[100]
 [200]
 [300]
 [400]
 [500]
 [600]
 [700]]
[5.71428571 5.71428571]
[2.18529408 1.90595201]
[[-0.32686023  1.72392288]
 [ 0.13074409 -1.42411021]
 [-1.69967317  0.67457852]
 [-0.78446454 -0.37476584]
 [ 1.04595272  0.67457852]
 [ 1.50355704 -0.37476584]
 [ 0.13074409 -0.89943803]]
[[ 1.         -0.32686023  1.72392288]
 [ 1.          0.13074409 -1.42411021]
 [ 1.         -1.69967317  0.67457852]
 [ 1.         -0.78446454 -0.37476584]
 [ 1.          1.04595272  0.67457852]
 [ 1.          1.50355704 -0.37476584]
 [ 1.          0.13074409 -0.89943803]]
[[0.]
 [0.]
 [0.]]
optimized weights: [[399.99999933]
 [ 83.72833373]
 [-63.57672945]]
Optimized coefficients (theta): [[ 83.72833373]
 [-63.57672945]]
Optimized intercept: [399.99999933]
   X1  X2
0   4   5
1   6   4
2   7   8
3   5   3
4   9   6
5   2   7
6   3   5


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
