In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

data=pd.read_csv('/content/drive/MyDrive/Task_1/Book1.csv')
print(data)

dataset1=data.iloc[:,0:1].values
print(dataset1)

dataset2=data.iloc[:,-1].values
print(dataset2)

x=np.array(dataset1)

y=np.array(dataset2)

scaler = preprocessing.MinMaxScaler()
normalized_features = scaler.fit_transform(x)
print(normalized_features)



   x  y
0  5  9
1  6  3
2  2  7
3  4  5
4  8  7
5  9  5
6  6  4
[[5]
 [6]
 [2]
 [4]
 [8]
 [9]
 [6]]
[9 3 7 5 7 5 4]
[[0.42857143]
 [0.57142857]
 [0.        ]
 [0.28571429]
 [0.85714286]
 [1.        ]
 [0.57142857]]
